version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my-app

hooks:
  BeforeInstall:
    - location: scripts/install_docker.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: ec2-user
